import os
import re
import sqlite3
from datetime import timedelta
from urllib.parse import urlparse
from dotenv import load_dotenv
from flask import Flask, flash, g, redirect, render_template, request, session, url_for
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect
from sqlalchemy import event
from sqlalchemy.engine import Engine
from werkzeug.exceptions import HTTPException, RequestEntityTooLarge
from werkzeug.middleware.proxy_fix import ProxyFix
from auth_account import (
    register_public_auth_routes,
    send_email_placeholder,
    user_has_admin_access,
)
from models import (
    User,
    db,
)
from helpers.core import (
    get_app_timezone_name,
    get_display_timezone_name,
    is_local_dev_environment,
    normalize_timezone_name,
    purge_expired_unverified_users,
    resolve_active_trade_account,
    sanitize_error_message,
)
from helpers.legal import LEGAL_LAST_UPDATED

from extensions import limiter
from routes import all_blueprints, mt5_internal_bp
from helpers.utils import env_bool, env_int, utcnow_naive

load_dotenv()


@event.listens_for(Engine, "connect")
def enable_sqlite_foreign_keys(dbapi_connection, _connection_record):
    if not isinstance(dbapi_connection, sqlite3.Connection):
        return
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()


def send_error_notification_email(error):
    error_to_email = os.getenv("ERROR_LOG_TO_EMAIL", "").strip().lower()
    if not error_to_email:
        return

    occurred_at = utcnow_naive().strftime("%Y-%m-%d %H:%M:%S UTC")
    app_env = os.getenv("APP_ENV", "").strip() or os.getenv("FLASK_ENV", "").strip() or "unknown"
    endpoint = request.endpoint or "-" if request else "-"
    route_pattern = request.url_rule.rule if request and request.url_rule else "-"
    method = request.method if request else "-"
    user_id = session.get("user_id", "-") if request else "-"
    remote_addr = (
        request.headers.get("X-Forwarded-For", "").split(",")[0].strip()
        or request.remote_addr
        or "-"
    ) if request else "-"
    subject = f"[FX Journal Error] {type(error).__name__} on {endpoint}"
    body = (
        "Unhandled application error\n\n"
        f"Occurred at: {occurred_at}\n"
        f"Environment: {app_env}\n"
        f"Method: {method}\n"
        f"Endpoint: {endpoint}\n"
        f"Route pattern: {route_pattern}\n"
        f"User ID: {user_id}\n"
        f"Client IP: {remote_addr}\n"
        f"Exception type: {type(error).__name__}\n"
        f"Exception message: {sanitize_error_message(error)}\n"
    )
    try:
        email_result = send_email_placeholder(error_to_email, subject, body)
        if not (email_result or {}).get("sent"):
            app.logger.warning(
                "Error notification email was not sent: to=%s subject=%s mode=%s",
                error_to_email,
                subject,
                (email_result or {}).get("mode", "unknown"),
            )
    except Exception as notify_exc:
        app.logger.warning("Error notification email failed: %s", notify_exc)

##Code was scaffolded by me, then heavily expanded and polished with the help of ChatGPT Codex. The overall architecture and ideas were done by me.
##HTML was generated by ChatGPT with some manual tweaks.
app = Flask(__name__)
if env_bool("TRUST_PROXY_HEADERS", default=not is_local_dev_environment()):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)
secret_key = os.getenv("SECRET_KEY")
if not secret_key:
    # Non-hardcoded fallback for local runs if .env is missing.
    secret_key = os.urandom(32).hex()
app.config["SECRET_KEY"] = secret_key
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
session_cookie_secure_override = os.getenv("SESSION_COOKIE_SECURE")
if session_cookie_secure_override is None:
    # Safe default: secure cookies in deployed/server environments,
    # relaxed for explicit local/dev mode.
    session_cookie_secure = not is_local_dev_environment()
else:
    session_cookie_secure = env_bool("SESSION_COOKIE_SECURE", False)
app.config["SESSION_COOKIE_SECURE"] = session_cookie_secure
app.config["PERMANENT_SESSION_LIFETIME"] = timedelta(days=30)
max_upload_mb = int(os.getenv("MAX_UPLOAD_MB", "4"))
app.config["MAX_CONTENT_LENGTH"] = max_upload_mb * 1024 * 1024

# Database URL placeholder flow:
# 1) Set DATABASE_URL in your environment for Postgres
# 2) If missing, fallback to local SQLite for development
database_url = os.getenv("DATABASE_URL", "sqlite:///FXJournal.db")
if database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql+psycopg://", 1)
elif database_url.startswith("postgresql://") and "+psycopg" not in database_url:
    database_url = database_url.replace("postgresql://", "postgresql+psycopg://", 1)

app.config["SQLALCHEMY_DATABASE_URI"] = database_url
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db.init_app(app)
migrate = Migrate(app, db, directory="migrations", compare_type=True)
csrf = CSRFProtect(app)
csrf.exempt(mt5_internal_bp)
# For production, set RATELIMIT_STORAGE_URI to Redis for shared counters.
app.config.setdefault("RATELIMIT_STORAGE_URI", os.getenv("RATELIMIT_STORAGE_URI", "memory://"))
limiter.init_app(app)

TOKEN_PURPOSE_VERIFY_EMAIL = "verify_email"
TOKEN_PURPOSE_PASSWORD_RESET = "password_reset"
CONTACT_CATEGORY_CHOICES = (
    "Feedback",
    "Bug Report",
    "Privacy / Data Issue",
    "Account / Access Issue",
    "General Enquiry",
    "Other",
)
CONTACT_EMAIL_RE = re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")
def _is_same_origin(url_value):
    parsed = urlparse(url_value)
    if parsed.scheme not in {"http", "https"}:
        return False
    return parsed.netloc == request.host


_last_purge_time = None


@app.before_request
def cleanup_expired_unverified_accounts():
    global _last_purge_time
    now = utcnow_naive()
    if not _last_purge_time or (now - _last_purge_time).total_seconds() >= 900:
        _last_purge_time = now
        purge_expired_unverified_users(app.logger)

    pending_email = session.get("pending_verify_email", "").strip().lower()
    if pending_email and not User.query.filter_by(email=pending_email).first():
        session.pop("pending_verify_email", None)
    return None


@app.before_request
def load_display_timezone_context():
    g.display_timezone_name = get_display_timezone_name()
    return None


@app.before_request
def load_trade_account_context():
    g.active_trade_account = None
    g.user_trade_accounts = []
    user_id = session.get("user_id")
    if not user_id:
        return None

    active_account, accounts = resolve_active_trade_account(user_id)
    g.active_trade_account = active_account
    g.user_trade_accounts = accounts
    return None


@app.before_request
def enforce_same_origin_for_authenticated_posts():
    if request.method != "POST":
        return None
    if not session.get("user_id"):
        return None

    origin = request.headers.get("Origin", "").strip()
    referer = request.headers.get("Referer", "").strip()
    if origin and not _is_same_origin(origin):
        return "Forbidden", 403
    if not origin and referer and not _is_same_origin(referer):
        return "Forbidden", 403
    return None


@app.context_processor
def inject_trade_account_context():
    current_user = None
    user_id = session.get("user_id")
    if user_id:
        current_user = User.query.filter_by(id=user_id).first()
    current_page_path = request.full_path.rstrip("?")
    if not current_page_path:
        current_page_path = request.path or url_for("dashboard.home")
    return {
        "active_trade_account": getattr(g, "active_trade_account", None),
        "header_trade_accounts": getattr(g, "user_trade_accounts", []),
        "display_timezone_name": getattr(g, "display_timezone_name", get_app_timezone_name()),
        "is_admin_user": user_has_admin_access(current_user),
        "current_page_path": current_page_path,
    }


@app.after_request
def set_security_headers(response):
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    return response


@app.route("/session/display-timezone", methods=["POST"])
def set_display_timezone():
    payload = request.get_json(silent=True) or {}
    timezone_name = normalize_timezone_name(
        payload.get("timezone") or request.form.get("timezone"),
        default=None,
    )
    if not timezone_name:
        return "", 400

    if session.get("display_timezone") != timezone_name:
        session["display_timezone"] = timezone_name
        session.modified = True
    return "", 204


@app.errorhandler(RequestEntityTooLarge)
def handle_large_upload(_error):
    if session.get("user_id"):
        flash(f"File too large. Max upload is {max_upload_mb} MB.", "error")
        return redirect(url_for("trades.new_trade"))
    return redirect(url_for("login"))


@app.errorhandler(429)
def handle_rate_limit(_error):
    if request.path == "/login":
        return (
            render_template(
                "login.html",
                title="Login | FX Journal",
                body_class="auth-layout",
                error="Too many sign-in attempts. Please wait a minute and try again.",
            ),
            429,
        )
    return "Too many requests. Please try again later.", 429


def render_error_page(status_code, heading, description, title=None):
    user_logged_in = bool(session.get("user_id"))
    primary_endpoint = "dashboard.home" if user_logged_in else "login"
    primary_label = "Back to Dashboard" if user_logged_in else "Go to Login"
    secondary_endpoint = "trades.trades" if user_logged_in else None
    secondary_label = "View Trades" if user_logged_in else None
    return (
        render_template(
            "error.html",
            title=title or f"{status_code} | FX Journal",
            status_code=status_code,
            heading=heading,
            description=description,
            primary_url=url_for(primary_endpoint),
            primary_label=primary_label,
            secondary_url=url_for(secondary_endpoint) if secondary_endpoint else None,
            secondary_label=secondary_label,
            request_path=request.path,
        ),
        status_code,
    )


@app.errorhandler(HTTPException)
def handle_http_error(error):
    page_content = {
        403: (
            "Access denied",
            "You do not have permission to view this page.",
            "403 | FX Journal",
        ),
        404: (
            "Page not found",
            "The page you requested does not exist or may have moved.",
            "404 | FX Journal",
        ),
        405: (
            "Method not allowed",
            "That action is not available for this page.",
            "405 | FX Journal",
        ),
    }
    heading, description, title = page_content.get(
        error.code,
        (
            error.name or "Request error",
            error.description or "Something went wrong while processing your request.",
            f"{error.code} | FX Journal" if error.code else "Error | FX Journal",
        ),
    )
    return render_error_page(error.code or 500, heading, description, title=title)


@app.errorhandler(Exception)
def handle_unexpected_error(error):
    app.logger.exception("Unhandled application error.", exc_info=error)
    send_error_notification_email(error)
    return render_error_page(
        500,
        "Something broke on our side",
        "The page could not be loaded right now. Please try again in a moment.",
        title="500 | FX Journal",
    )


register_public_auth_routes(
    app,
    limiter,
    legal_last_updated=LEGAL_LAST_UPDATED,
    token_purpose_verify_email=TOKEN_PURPOSE_VERIFY_EMAIL,
    token_purpose_password_reset=TOKEN_PURPOSE_PASSWORD_RESET,
    env_int=env_int,
    is_local_dev_environment=is_local_dev_environment,
    resolve_active_trade_account=resolve_active_trade_account,
)

for blueprint in all_blueprints:
    app.register_blueprint(blueprint)

from celery_app import init_celery

init_celery(app)











if __name__ == "__main__":
    debug_mode = os.getenv("FLASK_DEBUG", "0").strip().lower() in {"1", "true", "yes"}
    app.run(debug=debug_mode)
